### ISSUE TITLE
Incorrect SED fit in example #1

### ISSUE THREAD

**Issue by infinitron** [gdrouart/MrMoose#2]
Hi,

I'm trying to reproduce the SED fit using the fake data generated by ```example-1.py```. This is what I get using the default settings

![example 1 SED fit](https://i.ibb.co/yk2bYPP/fake-data1-fit.png)

I've also tried setting ```nwalkers```, ```nsteps``` to higher values and the result is still the same.

Also, when I try fitting the data generated using ```example_6.py```, I get the following error
```
sampler saved!
fit completed!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mrmoose.py", line 149, in SED_fit
    an.find_stats_fit(sampler, model_struct, fit_struct, data_struct)
  File "analysis.py", line 62, in find_stats_fit
    best_param = sampler.chain[bestML_index[0], bestML_index[1], :]
IndexError: index 36 is out of bounds for axis 1 with size 20
```
Can you help me with these issues, please?

**Comment by eretana** [comment]
Hello. Same problem here. Examples 1 and 2 not working. Did you receive any feedback from the developers?. Best, Edwin.

**Comment by infinitron** [comment]
Hi Edwin,
No! I haven't heard from them yet.

**Comment by gdrouart** [comment]
Hi everyone,
The other developer left astronomy, I am the only left. I am in parental leave at the moment, apologies for the delay. I will look into this problem shortly, but I think I know where the pb is coming from. Will push the fix asap.

**Comment by eretana** [comment]
Dear @gdrouart thanks for your reply. Your help is very appreciated.

**Comment by gdrouart** [comment]
Hi,
A first part answer: 
I had a look to example 1 (as generated by example_1.py). If I put 100 walkers and 200 steps recover the paper. When changing the number of steps and/or walkers, MrMoose will create new files. Here the file with the nsteps=20 and nwalkers=20:
![image](https://user-images.githubusercontent.com/22902215/71793364-893ded80-3077-11ea-8f4f-c44b3c770894.png)
and the file for  nsteps=200 and nwalkers=100. Note that you also have to update where the cut is made (here nsteps_cut=180):
![image](https://user-images.githubusercontent.com/22902215/71793361-8642fd00-3077-11ea-9681-29e4c3efe1b3.png)

**Comment by gdrouart** [comment]
The second problem is a bit more tricky as I cannot reproduce it, even when redownloading the master branche. Seen the error it seems to be related to the emcee chain. Which version of emcee do you have installed? MrMoose was designed during the v2.2 and from memory the v3 was released last year, and it seems couple of changes might trigger this type of errors. 

My advice to make your life easier would be to use MrMoose in a dedicated virtual environment as various updates of the packages these last two years (emcee, astropy, numpy) might create difficulties and conflicts with your up-to-date installation. If you are not familiar with virtual environment, ananconda is doing this very well. I plan on making the python3 version available as the next update (which should solve hopefully part of these problems), meanwhile, the only way to use MrMoose is a python 2.7 environment.
